### ISSUE TITLE
not explained what python initializer.py is doing

### ISSUE THREAD

**Issue by antonkulaga** [vermasrijan/srijan-gsoc-2020#11]
When I run:
```
python initializer.py
```
I get some metrics printed but it is not explained (neither in readme nor in stdout) what is exactly happening.
Also, if you have some metrics you should save them, i.e. by making dvc stage with metrics as one of the outputs

**Comment by vermasrijan** [comment]
Sure, Thanks for the suggestion Anton. 
I have updated the code now, and added info in the readme
