### ISSUE TITLE
do base path resolution in your notebooks

### ISSUE THREAD

**Issue by antonkulaga** [vermasrijan/srijan-gsoc-2020#12]
the way how user may run your notebooks can be different. For instance, I commonly run:
```
jupyter lab notebooks
```
In the same time in your notebooks you have hardcoded path and you do not check witch which base folder they are run
```
samples_path = 'data/gtex/v8_samples.parquet'
expressions_path = 'data/gtex/v8_expressions.parquet'
```
here the problem can be that the user will start with notebooks as base folder and in such case your code will crash miserable.
For this reason in the beginning of your notebook you sould Path(".").resolve() the folder where you are and then use it as a base for your pathes. If, for instance the user used notebooks working fodler you can just go base = Path("..")

**Comment by antonkulaga** [comment]
In my PR about dependencies I also fixed it https://github.com/vermasrijan/srijan-gsoc-2020/pulls

I wonder why are you using strings for pathes instead of pathlib? Pathlib can make pathes that will work both for windows and linux/max

**Comment by vermasrijan** [comment]
Sure, thank you for pointing it out! 
Have merged and resolved the PR
