### ISSUE TITLE
dependency hell

### ISSUE THREAD

**Issue by antonkulaga** [vermasrijan/srijan-gsoc-2020#7]
I you have issues with your dependency configuration, you use outdated versions and put to pip the packages that are available at conda-forge. I create a PR to fix it https://github.com/vermasrijan/srijan-gsoc-2020/pull/6 , could you test that it does not break anything?

**Comment by vermasrijan** [comment]
Thanks for pointing it out. I have tested it on Macos/linux and have resolved it
