### ISSUE TITLE
ugly zip

### ISSUE THREAD

**Issue by antonkulaga** [vermasrijan/srijan-gsoc-2020#8]
You currently use some zip with gtex (i.e. dvc get-url https://www.dropbox.com/s/cmxruuqi26zweeq/gtex.zip?dl=1 data/ -v ), however if I just blindly follow the instruction things will not work well, as it implies the zip file should be unzipped.
Why not using dvc remote and just dvc repro to do preprocessing?

**Comment by vermasrijan** [comment]
Sure, I have added dvc import-url now
